---
- name: Install npm global packages
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  loop: "{{ npm_global_packages }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install VS Code extensions
  ansible.builtin.command: code --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"
  loop_control:
    label: "{{ item }}"
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure gh as git credential helper
  ansible.builtin.command: gh auth setup-git
  register: gh_setup_result
  changed_when: false
  failed_when: gh_setup_result.rc != 0 and 'not logged into' not in gh_setup_result.stderr
