---
- name: Create Alfred preferences directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Alfred/Alfred.alfredpreferences/preferences"
    state: directory
    mode: "0755"

- name: Restore Alfred preferences plist
  ansible.builtin.copy:
    src: prefs.plist
    dest: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Alfred/Alfred.alfredpreferences/preferences/prefs.plist"
    mode: "0644"

- name: Restore Alfred features config
  ansible.builtin.copy:
    src: features/
    dest: "{{ ansible_facts['env']['HOME'] }}/Library/Application Support/Alfred/Alfred.alfredpreferences/preferences/features/"
    mode: "0644"
