---
- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: "{{ macos_show_hidden_files }}"
  notify: Restart Finder

- name: Minimize windows into application icon
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: "{{ macos_minimize_to_application }}"
  notify: Restart Dock

- name: Set git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Set git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Create screenshots folder
  ansible.builtin.file:
    path: "{{ macos_screenshots_folder }}"
    state: directory
    mode: "0755"

- name: Set screenshots save location
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ macos_screenshots_folder }}"
