---
- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: "{{ macos_show_hidden_files }}"
  notify: Restart Finder

- name: Minimize windows into application icon
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: "{{ macos_minimize_to_application }}"
  notify: Restart Dock

- name: Set git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Set git user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Copy global gitignore
  ansible.builtin.copy:
    src: gitignore_global
    dest: "{{ ansible_env.HOME }}/.gitignore"
    mode: "0644"

- name: Set global gitignore in git config
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_env.HOME }}/.gitignore"

- name: Create screenshots folder
  ansible.builtin.file:
    path: "{{ macos_screenshots_folder }}"
    state: directory
    mode: "0755"

- name: Set screenshots save location
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ macos_screenshots_folder }}"

- name: Finder - show all file extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  notify: Restart Finder

- name: Finder - show status bar
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  notify: Restart Finder

- name: Finder - use column view by default
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: clmv
  notify: Restart Finder

- name: Finder - disable extension change warning
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  notify: Restart Finder

- name: Finder - no .DS_Store on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
